CoolParking/CoolParking.WebUI/Models/ErrorViewModel.cs
using System;

namespace CoolParking.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoolParking/CoolParking.WebUI/Models/TopUpModel.cs
using System.Text.Json.Serialization;

namespace CoolParking.WebUI.Models
{
    public class TopUpModel
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("Sum")]
        public decimal Sum { get; set; }
    }
}

CoolParking/CoolParking.WebUI/Models/TransactionInfo.cs
using System;
using Newtonsoft.Json;

namespace CoolParking.WebUI.Models
{
    public class TransactionInfo
    {
        [JsonProperty("vehicleId")]
        public string VehicleId { get; set; }
        [JsonProperty("sum")]
        public decimal Sum { get; set; }
        [JsonProperty("transactionDate")]
        public DateTime Time { get; set; }
    }
}

CoolParking/CoolParking.WebUI/Models/Vehicle.cs
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace CoolParking.WebUI.Models
{
    public class Vehicle
    {
        [JsonProperty("id")]
        [RegularExpression(@"\A[A-Z][A-Z]-[0-9][0-9][0-9][0-9]-[A-Z][A-Z]\Z")]
        [Required]
        public string Id { get; set; }

        [JsonProperty("vehicleType")]
        public VehicleType VehicleType { get; set; }

        [JsonProperty("balance")]
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        [Required]
        public decimal Balance { get; set; }
    }
}

CoolParking/CoolParking.WebUI/Models/VehicleType.cs
namespace CoolParking.WebUI.Models
{
    public enum VehicleType
    {
        PassengerCar,
        Truck,
        Bus,
        Motorcycle
    }
}

CoolParking/CoolParking.WebUI/Controllers/ParkingController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoolParking.WebUI.Controllers
{
    public class ParkingController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using var client = new HttpClient();

            var capacityResponse = await client.GetAsync("https://localhost:44374/api/parking/capacity");
            ViewBag.Capacity = await capacityResponse.Content.ReadAsStringAsync();

            var balanceResponse = await client.GetAsync("https://localhost:44374/api/parking/balance");
            ViewBag.Balance = await balanceResponse.Content.ReadAsStringAsync();

            var freePlacesResponse = await client.GetAsync("https://localhost:44374/api/parking/freePlaces");
            ViewBag.FreePlaces = await freePlacesResponse.Content.ReadAsStringAsync();

            return View();
        }
    }
}

CoolParking/CoolParking.WebUI/Controllers/TransactionsController.cs
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using CoolParking.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CoolParking.WebUI.Controllers
{
    public class TransactionsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using var client = new HttpClient();

            var allResponse = await client.GetAsync("https://localhost:44374/api/transactions/all");
            if (allResponse.StatusCode == HttpStatusCode.NotFound)
            {
                ViewBag.AllTransactions = "Транзакцій не знайдено";
            }
            else
            {
                ViewBag.AllTransactions = await allResponse.Content.ReadAsStringAsync();
            }
            return View();
        }

        public async Task<IActionResult> LastTransactions()
        {
            using var client = new HttpClient();

            var lastResponse = await client.GetAsync("https://localhost:44374/api/transactions/last");
            var model = JsonConvert.DeserializeObject<List<TransactionInfo>>(await lastResponse.Content.ReadAsStringAsync());
            return View(model);
        }
    }
}

CoolParking/CoolParking.WebUI/Controllers/VehicleController.cs
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using CoolParking.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CoolParking.WebUI.Controllers
{
    public class VehicleController : Controller
    {
        public async Task<IActionResult> List()
        {
            using var client = new HttpClient();

            var vehicleResponse = await client.GetAsync("https://localhost:44374/api/vehicles");
            var model = JsonConvert.DeserializeObject<List<Vehicle>>(await vehicleResponse.Content.ReadAsStringAsync());
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,VehicleType,Balance")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                using var client = new HttpClient();

                var json = JsonConvert.SerializeObject(vehicle);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var addVehicleURL = "https://localhost:44374/api/vehicles";
                var response = await client.PostAsync(addVehicleURL, data);
                if (response.StatusCode== HttpStatusCode.Created)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewBag.ErrorMessage = "Парковку заповнено, або машина з такими номерами вже існує";
                    return View();
                }
            }

            return View(vehicle);
        }

        public async Task<IActionResult> Delete(string id)
        {
            using var client = new HttpClient();

            var vehicleDelete = await client.GetAsync($"https://localhost:44374/api/vehicles/{id}");
            var model = JsonConvert.DeserializeObject<Vehicle>(await vehicleDelete.Content.ReadAsStringAsync());
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteId(string id)
        {
            using var client = new HttpClient();

            var vehicleDelete = $"https://localhost:44374/api/vehicles/{id}";
            var response = await client.DeleteAsync(vehicleDelete);

            return RedirectToAction("List");
        }

        public IActionResult TopUp(string id)
        {
            return View(new TopUpModel
            {
                Id = id,
                Sum = 0
            });
        }

        [HttpPost]
        public async Task<IActionResult> TopUpVehicle(TopUpModel topUpModel)
        {
            using var client = new HttpClient();

            var json = JsonConvert.SerializeObject(topUpModel);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var addVehicleURL = "https://localhost:44374/api/transactions/topUpVehicle";
            var response = await client.PutAsync(addVehicleURL, data);
            return RedirectToAction("List");
        }
    }
}

CoolParking/CoolParking.WebUI/Views/Parking/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

    <h1>Всього мiсць на паркінгу: @ViewBag.Capacity</h1>
    <h1>Поточний баланс паркiнгу: @ViewBag.Balance</h1>
    <h1>На паркiнгу вiльних мiсць: @ViewBag.FreePlaces</h1>

CoolParking/CoolParking.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoolParking.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Parking" asp-action="Index">CoolParking.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parking" asp-action="Index">Parking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">All Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="List">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="LastTransactions">Last Transactions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CoolParking/CoolParking.WebUI/Views/Transactions/Index.cshtml
@{
    ViewData["Title"] = "All Transactions";
}

<h1>Транзакції: </h1>
<textarea readonly rows="20" class="text-area-width">@ViewBag.AllTransactions</textarea>

CoolParking/CoolParking.WebUI/Views/Transactions/LastTransactions.cshtml
@model IEnumerable<CoolParking.WebUI.Models.TransactionInfo>

@{
    ViewData["Title"] = "Create Vehicle";
}

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleId)
        </th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleId)
                </td>
            </tr>
        }
    </tbody>
</table>

CoolParking/CoolParking.WebUI/Views/Vehicle/Create.cshtml
@model CoolParking.WebUI.Models.Vehicle

@{
    ViewData["Title"] = "Create Vehicle";
}


<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleType" class="control-label"></label>
                @Html.DropDownList("VehicleType",
                    new SelectList(Enum.GetValues(typeof(VehicleType))),
                    new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group">
                <span class="text-danger">@ViewBag.ErrorMessage</span>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

CoolParking/CoolParking.WebUI/Views/Vehicle/Delete.cshtml
@model CoolParking.WebUI.Models.Vehicle

@{
    ViewData["Title"] = "Delete Vehicle";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
    </dl>
    
    <form asp-action="DeleteId"  asp-route-id="@Model.Id">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

CoolParking/CoolParking.WebUI/Views/Vehicle/List.cshtml
@model IEnumerable<CoolParking.WebUI.Models.Vehicle>

@{
    ViewData["Title"] = "Vehicles";
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                @Html.ActionLink("TopUp", "TopUp", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

CoolParking/CoolParking.WebUI/Views/Vehicle/TopUp.cshtml
@model CoolParking.WebUI.Models.TopUpModel

@{
    ViewData["Title"] = "TopUp";
}


<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="TopUpVehicle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input readonly asp-for="Id" class="form-control" />
            </div>
           
            <div class="form-group">
                <label asp-for="Sum" class="control-label"></label>
                <input asp-for="Sum" class="form-control" />
                <span asp-validation-for="Sum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>